backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", required: false}
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
  - name: "book"
    label: "book"
    folder: "src/book-queue/"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - label: "Books"
        name: "books"
        widget: "list"
        summary: "{{fields.title}} - {{fields.author}}"
        fields:
          - {label: "タイトル", name: "title", widget: "string", default: "書籍名"}
          - {label: "著者", name: "author", widget: "string", default: "著者名"}
          - {label: "追加日時", name: "created_at", widget: "datetime"}
          - {label: "読了日時", name: "read_at", widget: "datetime", default: ""}

